apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: staffservice
  name: staffservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: staffservice
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: staffservice
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-staff
            - name: POSTGRES_DB
              value: staffservice
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: bogdannaida/staff-service:latest
          imagePullPolicy: ""
          name: horse-service
          ports:
            - containerPort: 8084
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data-staff
          persistentVolumeClaim:
            claimName: postgres-data-staff
status: { }