version: '3.1'
services:
  staffservice:
    network_mode: bridge
    container_name: staffservice
    image: bogdannaida/staff-service:latest
    build: ..
    ports:
      - "8084:8084"
      - "9090:9090"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=staffservice
      - DB_SERVER=postgresqldb-staff
    links:
      - postgresqldb-staff

  postgresqldb-staff:
    network_mode: bridge
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=staffservice
    volumes:
      - postgres-data-horses:/home/bogdannaida/Projects/IntelliJ-projects/Volumes/
volumes:
  postgres-data-staff: