apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: staffservice
  name: staffservice
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: staffservice
status:
  loadBalancer: { }